name: Test
on:
    push:
    pull_request:

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install Zig
              uses: mlugg/setup-zig@v2
              with:
                  version: "0.15.1"

            - name: Test
              run: zig build test
